const projects = [
  {
    name: "Web Widgets",
    img: "webwidgets",
    desc: "A web application that allows you to personalize your browsing experience by adding customized widgets and creating dynamic layouts. ",
    technologies: ["Next.js, TailwindCSS, MongoDB, Next-Auth, NextUI"],
    live: "https://the-web-widgets.vercel.app/",
    code: "https://github.com/Dhruv883/WebWidgets",
    grpProj: true,
  },
  {
    name: "Story Craft",
    img: "storycraft",
    desc: "Simple blog site that allows users to create, read, update and delete their blogs. You can also search for blogs by title and tags.",
    technologies: [
      "React.js, Node.js, Express.js, MongoDB, Redux, TailwindCSS",
    ],
    live: "",
    code: "https://github.com/Dhruv883/Blog-App",
    grpProj: false,
  },
  {
    name: "Task Mate",
    img: "taskmate",
    desc: "Task list application that allows you to create projects with different priorities and create tasks for a specific project. Users can filter tasks by due date and change the status of the task ",
    technologies: ["React.js, Tailwind CSS, Loacal Storage"],
    live: "https://dhruv883-task-list.netlify.app/",
    code: "https://github.com/Dhruv883/Task-List",
    grpProj: false,
  },
  {
    name: "DocPlus",
    img: "docplus",
    desc: "Docplus is a web application that allows patients to view various specialities and doctors and book online appointments. It is built using HTML, CSS, JS, and PHP.",
    technologies: ["HTML, CSS, JavaScript, PHP, MySQL"],
    live: "",
    code: "https://github.com/Dhruv883/Hospital-Management-System",
    grpProj: true,
  },
  {
    name: "Dom's Kitchen",
    img: "domkitchen",
    desc: "DOM's Kitchen is a web application that allows customers to view and order various food items online. It is built using HTML, CSS, JS, and PHP.",
    technologies: ["HTML, CSS, JavaScript, PHP, MySQL"],
    live: "",
    code: "https://github.com/Dhruv883/Restaurant-Management-System",
    grpProj: true,
  },
  {
    name: "Weather App",
    img: "weather",
    desc: "Simple weather app to display the current weather of any city in the world in Fahrenheit and Celsius. Created with the OpenWeather API.",
    technologies: ["HTML, CSS, JavaScript, OpenWeather API"],
    live: "https://dhruv883.github.io/Weather-App/",
    code: "https://github.com/Dhruv883/Weather-App",
    grpProj: false,
  },
  {
    name: "Portfolio Website",
    img: "portfolio",
    desc: "My Personal Portfolio Website made using Next.js, TailwindCSS and framer motion for animations.",
    technologies: ["Next.js, TailwindCSS, Framer Motion"],
    live: "",
    code: "https://github.com/Dhruv883/Portfolio-website",
    grpProj: false,
  },
];

export default projects;
