const projects = [
  {
    name: "Web Widgets",
    img: "webwidgets",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos ipsa, illo officia alias eos qui veniam sint ipsam neque, accusantium voluptatum dolore corporis minima tempora, inventore iste a voluptatibus temporibus mollitia maiores. Modi, asperiores aperiam?",
    technologies: ["Next.js, TailwindCSS, MongoDB, Next-Auth, NextUI"],
    live: "https://the-web-widgets.vercel.app/",
    code: "https://github.com/Dhruv883/WebWidgets",
    grpProj: true,
  },
  {
    name: "Story Craft",
    img: "storycraft",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos ipsa, illo officia alias eos qui veniam sint ipsam neque, accusantium voluptatum dolore corporis minima tempora, inventore iste a voluptatibus temporibus mollitia maiores. Modi, asperiores aperiam?",
    technologies: [
      "React.js, Node.js, Express.js, MongoDB, Redux, TailwindCSS",
    ],
    live: "",
    code: "https://github.com/Dhruv883/Blog-App",
    grpProj: false,
  },
  {
    name: "Task Mate",
    img: "taskmate",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos ipsa, illo officia alias eos qui veniam sint ipsam neque, accusantium voluptatum dolore corporis minima tempora, inventore iste a voluptatibus temporibus mollitia maiores. Modi, asperiores aperiam?",
    technologies: ["React.js, Tailwind CSS, Loacal Storage"],
    live: "https://dhruv883-task-list.netlify.app/",
    code: "https://github.com/Dhruv883/Task-List",
    grpProj: false,
  },
  {
    name: "DocPlus",
    img: "docplus",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos ipsa, illo officia alias eos qui veniam sint ipsam neque, accusantium voluptatum dolore corporis minima tempora, inventore iste a voluptatibus temporibus mollitia maiores. Modi, asperiores aperiam?",
    technologies: ["HTML, CSS, JavaScript, PHP, MySQL"],
    live: "",
    code: "https://github.com/Dhruv883/Hospital-Management-System",
    grpProj: true,
  },
  {
    name: "Dom's Kitchen",
    img: "domkitchen",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos ipsa, illo officia alias eos qui veniam sint ipsam neque, accusantium voluptatum dolore corporis minima tempora, inventore iste a voluptatibus temporibus mollitia maiores. Modi, asperiores aperiam?",
    technologies: ["HTML, CSS, JavaScript, PHP, MySQL"],
    live: "",
    code: "https://github.com/Dhruv883/Restaurant-Management-System",
    grpProj: true,
  },
  {
    name: "Weather App",
    img: "weather",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos ipsa, illo officia alias eos qui veniam sint ipsam neque, accusantium voluptatum dolore corporis minima tempora, inventore iste a voluptatibus temporibus mollitia maiores. Modi, asperiores aperiam?",
    technologies: ["HTML, CSS, JavaScript, APIs"],
    live: "https://dhruv883.github.io/Weather-App/",
    code: "https://github.com/Dhruv883/Weather-App",
    grpProj: false,
  },
  {
    name: "Portfolio Website",
    img: "portfolio",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos ipsa, illo officia alias eos qui veniam sint ipsam neque, accusantium voluptatum dolore corporis minima tempora, inventore iste a voluptatibus temporibus mollitia maiores. Modi, asperiores aperiam?",
    technologies: ["Next.js, TailwindCSS, Framer Motion"],
    live: "",
    code: "",
    grpProj: false,
  },
];

export default projects;
